; platformio.ini -------------------------------------------------
[env:esp32dev]
platform = espressif32
board    = esp32dev          ; DOIT DevKit V1 (30‑pin)
framework = arduino
monitor_speed = 115200

; -----------  Thư viện  -----------------------------------------
lib_deps =
    adafruit/DHT sensor library @ ^1.4.7
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.7
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.17
    madhephaestus/ESP32Servo @ ^3.0.5